language: Dart

ignore_all_files_in_gitignore: true
ignored_paths: []

read_only: false

excluded_tools: []

initial_prompt: |
  AllergyGuard は日本人が海外で外食する際のアレルギー対応支援Flutterアプリです。

  主要機能:
  1. レストランメニューをカメラで撮影
  2. OCRでテキストを認識
  3. 自動で日本語に翻訳
  4. 登録したアレルギー情報と照合
  5. 危険な料理に警告表示

  最初のMVPとして、カメラ撮影→OCR→翻訳→アレルギーチェックの基本フローを実装します。

project_name: "allergy_guard"
